export const BOOK_TRIP_REQUEST = "BOOK_TRIP_REQUEST";
export const BOOK_TRIP_SUCCESS = "BOOK_TRIP_SUCCESS";
export const BOOK_TRIP_FAIL = "BOOK_TRIP_FAIL";
export const BOOK_TRIP_RESET = "BOOK_TRIP_RESET";

export const USER_BOOKINGS_REQUEST = "USER_BOOKINGS_REQUEST";
export const USER_BOOKINGS_SUCCESS = "USER_BOOKINGS_SUCCESS";
export const USER_BOOKINGS_FAIL = "USER_BOOKINGS_FAIL";

export const BOOKING_DELETE_REQUEST = "BOOKING_DELETE_REQUEST";
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL";
