export const REQUEST_TRIP_LIST_REQUEST = "REQUEST_TRIP_LIST_REQUEST";
export const REQUEST_TRIP_LIST_SUCCESS = "REQUEST_TRIP_LIST_SUCCESS";
export const REQUEST_TRIP_LIST_FAIL = "REQUEST_TRIP_LIST_FAIL";

export const GET_ONE_REQUEST_TRIP = "GET_ONE_REQUEST_TRIP";
