export const REQUEST_TRIP_LIST_REQUEST = "REQUEST_TRIP_LIST_REQUEST";
export const REQUEST_TRIP_LIST_SUCCESS = "REQUEST_TRIP_LIST_SUCCESS";
export const REQUEST_TRIP_LIST_FAIL = "REQUEST_TRIP_LIST_FAIL";

export const GET_ONE_REQUEST_TRIP = "GET_ONE_REQUEST_TRIP";
export const ONE_REQUEST_RESET = "ONE_REQUEST_RESET";

export const CREATE_REQUEST_TRIP_REQUEST = "CREATE_REQUEST_TRIP_REQUEST";
export const CREATE_REQUEST_TRIP_SUCCESS = "CREATE_REQUEST_TRIP_SUCCESS";
export const CREATE_REQUEST_TRIP_FAIL = "CREATE_REQUEST_TRIP_FAIL";
export const CREATE_REQUEST_TRIP_RESET = "CREATE_REQUEST_TRIP_RESET";

export const USER_REQUESTS_REQUEST = "USER_REQUESTS_REQUEST";
export const USER_REQUESTS_SUCCESS = "USER_REQUESTS_SUCCESS";
export const USER_REQUESTS_FAIL = "USER_REQUESTS_FAIL";

export const REQUEST_UPDATE_REQUEST = "REQUEST_UPDATE_REQUEST";
export const REQUEST_UPDATE_SUCCESS = "REQUEST_UPDATE_SUCCESS";
export const REQUEST_UPDATE_FAIL = "REQUEST_UPDATE_FAIL";
export const REQUEST_UPDATE_RESET = "REQUEST_UPDATE_RESET";

export const REQUEST_DELETE_REQUEST = "REQUEST_DELETE_REQUEST";
export const REQUEST_DELETE_SUCCESS = "REQUEST_DELETE_SUCCESS";
export const REQUEST_DELETE_FAIL = "REQUEST_DELETE_FAIL";
