export const TRIP_LIST_REQUEST = "TRIP_LIST_REQUEST";
export const TRIP_LIST_SUCCESS = "TRIP_LIST_SUCCESS";
export const TRIP_LIST_FAIL = "TRIP_LIST_FAIL";

export const GET_ONE_TRIP = "GET_ONE_TRIP";
export const TRIP_RESET = "TRIP_RESET";

export const TRIP_CREATE_REQUEST = "TRIP_CREATE_REQUEST";
export const TRIP_CREATE_SUCCESS = "TRIP_CREATE_SUCCESS";
export const TRIP_CREATE_FAIL = "TRIP_CREATE_FAIL";
export const TRIP_CREATE_RESET = "TRIP_CREATE_RESET";

export const USER_TRIPS_REQUEST = "USER_TRIPS_REQUEST";
export const USER_TRIPS_SUCCESS = "USER_TRIPS_SUCCESS";
export const USER_TRIPS_FAIL = "USER_TRIPS_FAIL";

export const TRIP_UPDATE_REQUEST = "TRIP_UPDATE_REQUEST";
export const TRIP_UPDATE_SUCCESS = "TRIP_UPDATE_SUCCESS";
export const TRIP_UPDATE_FAIL = "TRIP_UPDATE_FAIL";
export const TRIP_UPDATE_RESET = "TRIP_UPDATE_RESET";

export const TRIP_DELETE_REQUEST = "TRIP_DELETE_REQUEST";
export const TRIP_DELETE_SUCCESS = "TRIP_DELETE_SUCCESS";
export const TRIP_DELETE_FAIL = "TRIP_DELETE_FAIL";
